export interface ProductReview {
  reviewer: string
  country: string
  date: string
  rating: number
  text: string
  verified: boolean
}

export interface Product {
  id: string
  slug: string
  image: string
  title: string
  summary: string
  location: string
  category: string
  description?: string
  activities?: string[]
  highlights: string[]
  includes: string[]
  badge?: string
  duration: string
  features?: string[]
  bookedText?: string
  rating: number
  reviews: number
  price: number
  currency: string
  highlightedReviews?: ProductReview[]
}

export const products: Product[] = [
  {
    id: "1",
    slug: "cappadocia-sunrise-balloon-flight",
    image: "https://images.pexels.com/photos/34012271/pexels-photo-34012271.jpeg?cs=srgb&dl=pexels-photo4artt-34012271.jpg&fm=jpg",
    title: "Cappadocia: Sunrise Hot Air Balloon Flight with Champagne",
    summary:
      "See Cappadocia valleys at sunrise with hotel pickup and post-flight celebration.",
    location: "Cappadocia",
    category: "Adventure",
    description:
      "Cappadocia is one of Turkey's most surreal landscapes — ancient volcanic eruptions sculpted a fantasy world of fairy chimneys, cave dwellings, and sweeping valleys. A sunrise hot air balloon flight is the quintessential way to witness this UNESCO-listed region at its most magical: golden light pouring across the Göreme plateau as the valley below stirs to life.",
    activities: [
      "Sunrise hot air balloon flight over Göreme",
      "Hike through Rose Valley and Red Valley",
      "Explore Kaymakli Underground City",
      "Visit Göreme Open Air Museum",
      "Pottery workshop in Avanos",
      "ATV tour through fairy chimneys",
      "Horse riding at sunset in Love Valley",
    ],
    highlights: [
      "Sunrise flight over Goreme and Red Valley",
      "Licensed pilot and safety briefing included",
      "Hotel pickup and return transfer",
    ],
    includes: [
      "Roundtrip transfer",
      "Flight certificate",
      "Light refreshments",
    ],
    badge: "AI Recommended",
    duration: "3 hours",
    features: ["Hotel pickup included", "Small group"],
    bookedText: "Booked 50 times today",
    rating: 4.9,
    reviews: 1250,
    price: 150,
    currency: "EUR",
    highlightedReviews: [
      {
        reviewer: "Sarah",
        country: "Australia",
        date: "February 14, 2026",
        rating: 5,
        text: "Absolutely breathtaking! Watching the sun rise over the fairy chimneys from the balloon basket is something I will never forget. The pilot was incredibly professional and the champagne celebration at the end was a perfect touch.",
        verified: true,
      },
      {
        reviewer: "Marco",
        country: "Italy",
        date: "January 28, 2026",
        rating: 5,
        text: "The most magical experience of our Turkey trip. We woke up at 4am and it was worth every second. The team was organised, safe, and passionate about sharing Cappadocia's beauty. Book the private basket — it's worth the upgrade.",
        verified: true,
      },
    ],
  },
  {
    id: "2",
    slug: "istanbul-hagia-sophia-blue-mosque-topkapi-tour",
    image: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    title: "Istanbul: Hagia Sophia, Blue Mosque & Topkapi Palace Tour",
    summary:
      "Guided Istanbul old-city route covering Ottoman and Byzantine landmarks.",
    location: "Istanbul",
    category: "Culture",
    description:
      "Istanbul is the only city in the world straddling two continents, and its layered history is written across every skyline. From the Byzantine grandeur of the Hagia Sophia to the Ottoman splendour of the Topkapi Palace, the old city packs more world-class monuments per square kilometre than almost anywhere on earth.",
    activities: [
      "Tour Hagia Sophia and the Blue Mosque",
      "Explore Topkapi Palace and the harem",
      "Wander the Grand Bazaar's 4,000+ shops",
      "Sample street food in Eminonu",
      "Bosphorus sunset cruise",
      "Visit Dolmabahce Palace",
      "Spice Bazaar shopping tour",
    ],
    highlights: [
      "Skip long entry lines with pre-planned route",
      "Professional English-speaking guide",
      "Context on empire, architecture, and daily life",
    ],
    includes: ["Guide", "Planned entry sequence", "Old-city walking route"],
    badge: "Top Cultural Pick",
    duration: "4 hours",
    features: ["Skip the ticket line", "Expert Guide"],
    rating: 4.8,
    reviews: 3200,
    price: 45,
    currency: "EUR",
    highlightedReviews: [
      {
        reviewer: "John",
        country: "United States",
        date: "February 26, 2026",
        rating: 5,
        text: "Incredible experience that brought the scale and wonder of history to life. Our guide Mehmet was knowledgeable, funny, and incredibly passionate about Ottoman culture. Skipping the lines made the whole day stress-free.",
        verified: true,
      },
      {
        reviewer: "Aleksandrs",
        country: "United Kingdom",
        date: "January 19, 2026",
        rating: 5,
        text: "Everything was so nice and smooth. Me and my wife enjoyed everything. Thank you very much for a lovely interesting day. The guide was excellent and patient with our questions.",
        verified: true,
      },
    ],
  },
  {
    id: "3",
    slug: "ephesus-small-group-tour-kusadasi-izmir",
    image: "https://images.pexels.com/photos/36122307/pexels-photo-36122307.jpeg?cs=srgb&dl=pexels-hobiphotography-36122307.jpg&fm=jpg",
    title: "Ephesus: Small Group Tour from Kusadasi/Izmir",
    summary:
      "Visit major Ephesus ruins with transfers and commentary in a small group.",
    location: "Ephesus",
    category: "History",
    description:
      "Ephesus was one of the greatest cities of the ancient world — a Roman metropolis of 250,000 people and home to one of the Seven Wonders of the World. Walking its marble streets today is an extraordinary encounter with antiquity: the Library of Celsus, the Great Theatre, and the Terrace Houses are all remarkably preserved.",
    activities: [
      "Explore the Library of Celsus ruins",
      "Walk the Arcadian Way to the Great Theatre",
      "Visit the Terrace Houses (upper city mansions)",
      "See the remains of the Temple of Artemis",
      "Day trip to the House of the Virgin Mary",
      "Selcuk Archaeological Museum visit",
      "Browse the Selcuk Saturday market",
    ],
    highlights: [
      "Library of Celsus and Great Theatre stop",
      "Smaller group for flexible pacing",
      "Ideal for cruise and city visitors",
    ],
    includes: ["Transport", "Guide", "Lunch"],
    badge: "Best Value",
    duration: "6 hours",
    features: ["Lunch included", "Historical insights"],
    bookedText: "Popular with history buffs",
    rating: 4.7,
    reviews: 890,
    price: 60,
    currency: "EUR",
    highlightedReviews: [
      {
        reviewer: "Linda",
        country: "Canada",
        date: "March 1, 2026",
        rating: 5,
        text: "Ephesus is incredible and our guide made it come alive. Walking down the Marble Road knowing that millions of Romans walked the same path was goosebump-inducing. The small group size was perfect — no rushing, lots of time to explore.",
        verified: true,
      },
      {
        reviewer: "Pieter",
        country: "Netherlands",
        date: "February 8, 2026",
        rating: 4,
        text: "Wonderful tour, very well organised. The Library of Celsus is even more impressive in person. The lunch included was a bonus. My only small note is that it was busy mid-morning — if they offered a dawn slot that would be perfect.",
        verified: true,
      },
    ],
  },
  {
    id: "4",
    slug: "pamukkale-hierapolis-full-day-tour",
    image: "https://images.pexels.com/photos/34215958/pexels-photo-34215958.jpeg?cs=srgb&dl=pexels-missptr-34215958.jpg&fm=jpg",
    title: "Pamukkale & Hierapolis Full-Day Guided Tour",
    summary:
      "Discover travertine terraces and the ancient spa city of Hierapolis.",
    location: "Pamukkale",
    category: "Nature",
    description:
      "Pamukkale — meaning 'Cotton Castle' in Turkish — is a natural wonder unlike anything else on earth. Mineral-rich thermal waters have cascaded down the hillside for millennia, creating a brilliant white landscape of terraced pools. Above them sits Hierapolis, an ancient Greco-Roman spa city whose residents paid to soak in the same healing waters.",
    activities: [
      "Wade through the travertine thermal pools",
      "Explore Hierapolis ancient ruins and theatre",
      "Swim in Cleopatra's Antique Pool",
      "Visit the vast Hierapolis necropolis",
      "Sunset viewing at the white terraces",
      "Day trip to Laodikeia ancient city",
      "Kaklik Cave stalactite excursion",
    ],
    highlights: [
      "Terrace viewpoints and UNESCO guidance",
      "Ancient baths and theatre access",
      "Comfortable day schedule with transport",
    ],
    includes: ["Transport", "Guide", "Free time at terraces"],
    badge: "Natural Wonder",
    duration: "8 hours",
    features: ["Transport included", "Swimming option"],
    rating: 4.6,
    reviews: 650,
    price: 55,
    currency: "EUR",
  },
  {
    id: "5",
    slug: "bodrum-blue-voyage-gulet-cruise",
    image: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    title: "Bodrum: Blue Voyage Gulet Cruise with Lunch",
    summary:
      "Sail the Aegean on a traditional wooden gulet, visiting hidden coves and crystal bays.",
    location: "Bodrum",
    category: "Adventure",
    description:
      "Bodrum has captivated visitors since antiquity — it was home to one of the Seven Wonders of the World, the Mausoleum at Halicarnassus. Today it thrives as the Aegean's most glamorous resort town, balancing its ancient harbour, crusader castle, and vibrant marina with pristine turquoise waters and legendary nightlife.",
    activities: [
      "Gulet blue voyage cruise to hidden coves",
      "Tour Bodrum Castle and the Underwater Museum",
      "Visit the Mausoleum at Halicarnassus ruins",
      "Snorkel and swim at Kara Ada island",
      "Explore Bodrum harbour market",
      "Sunset cocktails at the Bodrum windmills",
      "Day trip to Gumbet or Bitez beach",
    ],
    highlights: [
      "Visit Kara Ada hot springs and sea caves",
      "Swimming and snorkeling in turquoise waters",
      "Traditional Turkish lunch on board",
    ],
    includes: ["Lunch", "Snorkeling equipment", "Transfers from Bodrum centre"],
    badge: "Bestseller",
    duration: "8 hours",
    features: ["Lunch included", "Small group"],
    bookedText: "Booked 30 times today",
    rating: 4.8,
    reviews: 720,
    price: 40,
    currency: "EUR",
  },
  {
    id: "6",
    slug: "antalya-old-town-waterfall-tour",
    image: "https://images.pexels.com/photos/31914566/pexels-photo-31914566.jpeg?cs=srgb&dl=pexels-eren-31914566.jpg&fm=jpg",
    title: "Antalya: Old Town, Duden Waterfalls & Cable Car",
    summary:
      "Explore Kaleici harbour, ride the Tunektepe cable car, and admire Duden Waterfalls.",
    location: "Antalya",
    category: "Nature",
    description:
      "Antalya is Turkey's turquoise coast capital — a sun-drenched city where Roman walls, Ottoman minarets, and Taurus Mountain backdrops frame the sparkling Mediterranean. Gateway to world-class beaches and ancient ruins, it balances urban culture with natural spectacle, from the thundering Düden Waterfalls to the panoramic Tünektepe cable car.",
    activities: [
      "Walk the historic Kaleiçi old quarter",
      "Ride the Tünektepe cable car for panoramic views",
      "Visit the Upper and Lower Düden Waterfalls",
      "Explore the ancient ruins of Perge",
      "Day trip to Aspendos Roman theatre",
      "Relax on Lara or Konyaalti beach",
      "Water activities at Konyaalti beach park",
    ],
    highlights: [
      "Guided walk through Roman-era Kaleici lanes",
      "Panoramic Taurus Mountain cable car ride",
      "Upper and Lower Duden Waterfall viewpoints",
    ],
    includes: ["Cable car ticket", "Guide", "Hotel pick-up"],
    badge: "Top Rated",
    duration: "7 hours",
    features: ["Hotel pickup", "Cable car included"],
    rating: 4.7,
    reviews: 540,
    price: 35,
    currency: "EUR",
  },
  {
    id: "7",
    slug: "bursa-grand-mosque-silk-market-tour",
    image: "https://images.pexels.com/photos/19792501/pexels-photo-19792501.jpeg?cs=srgb&dl=pexels-zeynep-gonul-kocak-896406907-19792501.jpg&fm=jpg",
    title: "Bursa: Grand Mosque, Silk Bazaar & Green Tomb Tour",
    summary:
      "Discover the first Ottoman capital — magnificent mosques, covered bazaars, and royal tombs.",
    location: "Bursa",
    category: "Culture",
    description:
      "Bursa holds a special place in Turkish history as the first capital of the Ottoman Empire. Its skyline is defined by magnificent mosques, and its valleys are laced with thermal baths running since antiquity. Known as the 'Green City' for its lush parks, Bursa is also the birthplace of the iskender kebab and home to Turkey's finest silk.",
    activities: [
      "Visit Ulu Cami Grand Mosque with 20 domes",
      "Shop for silk at the Koza Han silk bazaar",
      "Explore the Green Mosque and Green Tomb",
      "Ride the gondola up to Uludağ mountain",
      "Soak in Çekirge Ottoman thermal baths",
      "Taste authentic iskender kebab",
      "Explore the Kapalı Çarşı old bazaar district",
    ],
    highlights: [
      "Ulu Cami Grand Mosque with 20 domes",
      "Silk bazaar and traditional Bursa silk scarves",
      "Green Mosque and Green Tomb of Sultan Mehmed I",
    ],
    includes: ["Guide", "Transport", "Bazaar walking route"],
    badge: "Hidden Gem",
    duration: "5 hours",
    features: ["Expert guide", "Transport included"],
    rating: 4.6,
    reviews: 310,
    price: 30,
    currency: "EUR",
  },
  {
    id: "8",
    slug: "ankara-anitkabir-museum-anatolian-civilizations",
    image: "https://images.pexels.com/photos/19197366/pexels-photo-19197366.jpeg?cs=srgb&dl=pexels-turuncu-sakal-523826045-19197366.jpg&fm=jpg",
    title: "Ankara: Ataturk Mausoleum & Museum of Anatolian Civilizations",
    summary:
      "Visit Turkey's capital landmarks — the Anitkabir mausoleum and the world-class Anatolian Civilizations Museum.",
    location: "Ankara",
    category: "History",
    description:
      "Ankara is more than Turkey's administrative capital — it is home to the most powerful monument in the country, the Anıtkabir mausoleum of Mustafa Kemal Atatürk, and the world-renowned Museum of Anatolian Civilizations. While often overlooked by international tourists, Ankara rewards visitors with genuine historical and cultural depth spanning 10,000 years.",
    activities: [
      "Pay respects at Anıtkabir mausoleum",
      "Explore the Museum of Anatolian Civilizations",
      "Visit Ankara Citadel and old town (Ulus)",
      "See Kocatepe Mosque architecture",
      "Browse Atpazarı antique district",
      "Day trip to Gordion (ancient Phrygian capital)",
      "Sample Ankara tava and local cuisine",
    ],
    highlights: [
      "Anitkabir: Ataturk's monumental mausoleum",
      "Artefacts spanning Paleolithic to Ottoman eras",
      "Hittite and Phrygian gallery highlights",
    ],
    includes: ["Museum ticket", "Guide", "City transport"],
    badge: "Cultural Must-See",
    duration: "6 hours",
    features: ["Museum tickets included", "Expert guide"],
    rating: 4.7,
    reviews: 425,
    price: 28,
    currency: "EUR",
  },
  {
    id: "9",
    slug: "trabzon-sumela-monastery-black-sea-tour",
    image: "https://images.pexels.com/photos/35165112/pexels-photo-35165112.jpeg?cs=srgb&dl=pexels-kadernamuslu-35165112.jpg&fm=jpg",
    title: "Trabzon: Sumela Monastery & Black Sea Highlands",
    summary:
      "Trek to the cliff-carved Sumela Monastery and explore the lush Black Sea highland plateau.",
    location: "Trabzon",
    category: "Adventure",
    description:
      "Trabzon sits on the Black Sea coast where mountains tumble steeply into the sea, creating a dramatic landscape of misty peaks and lush highland plateaus. Once a Silk Road city and seat of a brilliant Byzantine empire, its most famous treasure — the Sumela Monastery — clings impossibly to a sheer cliff face in the Pontic Alps, one of the most striking sights in all Turkey.",
    activities: [
      "Trek to Sumela Monastery on its sheer cliff face",
      "Scenic drive to Uzungöl alpine lake",
      "Visit Trabzon Hagia Sophia church-mosque",
      "Explore Atatürk's Trabzon villa",
      "Hike the Karadağ plateau trails",
      "Taste Trabzon pide and Black Sea anchovies",
      "Day trip to Ayder hot spring plateau",
    ],
    highlights: [
      "Sumela Monastery at 1200 m on a sheer cliff face",
      "Uzungol alpine lake scenic drive",
      "Traditional Black Sea breakfast included",
    ],
    includes: ["Monastery entry", "Breakfast", "Transport"],
    badge: "Off the Beaten Path",
    duration: "9 hours",
    features: ["Breakfast included", "Scenic mountain drive"],
    bookedText: "Popular with nature lovers",
    rating: 4.8,
    reviews: 290,
    price: 38,
    currency: "EUR",
  },
  {
    id: "10",
    slug: "konya-mevlana-museum-whirling-dervish",
    image: "https://images.pexels.com/photos/19792501/pexels-photo-19792501.jpeg?cs=srgb&dl=pexels-zeynep-gonul-kocak-896406907-19792501.jpg&fm=jpg",
    title: "Konya: Mevlana Museum & Sema Whirling Dervish Ceremony",
    summary:
      "Experience the spiritual heart of Turkey — the Mevlana Museum and a live Sema ceremony.",
    location: "Konya",
    category: "Culture",
    description:
      "Konya is one of Turkey's oldest continuously inhabited cities and the spiritual home of Sufism. This is where the 13th-century mystic poet Rumi lived, taught, and is buried — and his presence still shapes the city profoundly. Watching a live Sema ceremony — the whirling dervish ritual — is an unforgettable spiritual experience found nowhere else like this.",
    activities: [
      "Visit Mevlana Museum and Rumi's tomb",
      "Watch a live Sema whirling dervish ceremony",
      "Explore Alaeddin Mosque on the citadel",
      "Tour Karatay Ceramics Museum",
      "Day trip to Çatalhöyük Neolithic site",
      "Taste Konya etli ekmek flatbread",
      "See İnce Minaret Seljuk architecture",
    ],
    highlights: [
      "Mevlana Museum: resting place of Rumi",
      "Live Sema whirling dervish performance",
      "Karatay Ceramics Museum",
    ],
    includes: ["Museum entry", "Ceremony ticket", "Guide"],
    badge: "Spiritual Experience",
    duration: "5 hours",
    features: ["Ceremony included", "Expert guide"],
    rating: 4.7,
    reviews: 380,
    price: 32,
    currency: "EUR",
  },
  {
    id: "11",
    slug: "troy-ancient-ruins-canakkale-tour",
    image: "https://images.pexels.com/photos/36122307/pexels-photo-36122307.jpeg?cs=srgb&dl=pexels-hobiphotography-36122307.jpg&fm=jpg",
    title: "Troy Ancient Ruins & Gallipoli Battlefield Day Tour",
    summary:
      "Walk through the legendary ruins of Troy and pay tribute at Gallipoli's WWI memorials.",
    location: "Canakkale",
    category: "History",
    description:
      "Few places on earth carry the weight of legend that Troy does. Immortalised in Homer's Iliad, the archaeological site reveals nine distinct civilisations layered over 4,000 years. Nearby, the Gallipoli Peninsula is one of WWI's most significant battlefields — a place of deep pilgrimage for Australians, New Zealanders, and Turks who share a profound respect for the fallen.",
    activities: [
      "Walk Troy UNESCO ruins and the replica wooden horse",
      "Visit Gallipoli Anzac Cove and WWI memorials",
      "Ferry crossing of the Dardanelles",
      "See the Chunuk Bair New Zealand memorial",
      "Lone Pine cemetery and battlefield walk",
      "Visit the Çanakkale Archaeology Museum",
      "Explore Çanakkale waterfront and clock tower",
    ],
    highlights: [
      "Troy UNESCO site with replica wooden horse",
      "Gallipoli Anzac Cove and Chunuk Bair",
      "Expert historian commentary throughout",
    ],
    includes: ["Entry tickets", "Historian guide", "Ferry crossing"],
    badge: "History Lovers Pick",
    duration: "10 hours",
    features: ["Ferry included", "Expert historian"],
    rating: 4.6,
    reviews: 510,
    price: 65,
    currency: "EUR",
  },
  {
    id: "12",
    slug: "istanbul-bosphorus-cruise-two-continents",
    image: "https://images.pexels.com/photos/31661448/pexels-photo-31661448.jpeg?cs=srgb&dl=pexels-pelin-2937827-31661448.jpg&fm=jpg",
    title: "Istanbul: Bosphorus Cruise — Two Continents in One Day",
    summary:
      "Glide along the Bosphorus Strait, spotting palaces, fortresses, and the bridge between Europe and Asia.",
    location: "Istanbul",
    category: "Culture",
    description:
      "The Bosphorus Strait is Istanbul's liquid spine — the narrow waterway separating Europe from Asia that has been one of history's most strategically significant passages for 3,000 years. Cruising it reveals Istanbul from an angle no street can offer: Ottoman palaces rising directly from the water, medieval fortresses perched on cliffs, and elegant wooden waterfront mansions lining both shores.",
    activities: [
      "Bosphorus cruise past palaces and fortresses",
      "Visit Dolmabahçe Palace grounds",
      "Cross to the Asian side: Üsküdar and Kadıköy",
      "Explore Rumeli Hisarı fortress",
      "Fish sandwich lunch at Eminönü docks",
      "Browse Ortaköy Sunday market",
      "Evening waterfront dinner at Bebek",
    ],
    highlights: [
      "Dolmabahce Palace waterfront view",
      "Rumeli Fortress from the water",
      "Fish market lunch stop in Eminonu",
    ],
    includes: ["Boat cruise", "Audio guide", "Port transfers"],
    badge: "Most Popular",
    duration: "3.5 hours",
    features: ["Scenic cruise", "Audio guide"],
    bookedText: "Booked 80 times today",
    rating: 4.8,
    reviews: 4100,
    price: 25,
    currency: "EUR",
  },
  {
    id: "13",
    slug: "izmir-agora-kordon-winery-tour",
    image: "https://images.pexels.com/photos/36122307/pexels-photo-36122307.jpeg?cs=srgb&dl=pexels-hobiphotography-36122307.jpg&fm=jpg",
    title: "Izmir: Ancient Agora, Kadifekale & Kordon Waterfront Tour",
    summary:
      "Explore Turkey's third-largest city — walk Roman ruins, climb a fortress hill, and stroll the sparkling Aegean waterfront.",
    location: "Izmir",
    category: "Culture",
    description:
      "Izmir — ancient Smyrna — is Turkey's most cosmopolitan city: a sun-lit, liberal Aegean port where palm-lined boulevards meet Roman ruins, and café terraces face a glittering bay. One of the oldest continuously inhabited cities on earth, Izmir blends layers of Greek, Roman, Byzantine, Ottoman, and modern Turkish identity into a uniquely relaxed and welcoming character.",
    activities: [
      "Explore the Roman Agora of Smyrna",
      "Climb Kadifekale fortress for panoramic bay views",
      "Walk the Kordon waterfront promenade",
      "Browse Kemeraltı historical bazaar",
      "Day trip to Çeşme beach resort",
      "Visit Izmir Archaeological Museum",
      "Wine tasting at a local Aegean winery",
    ],
    highlights: [
      "Roman Agora of Smyrna — one of Turkey's best-preserved",
      "Kadifekale hill fortress with Aegean panorama",
      "Lively Kemeraltı bazaar and Kordon waterfront",
    ],
    includes: ["Guide", "Transport", "Museum entry"],
    badge: "Coastal Gem",
    duration: "6 hours",
    features: ["Seafront city", "Expert guide"],
    rating: 4.7,
    reviews: 460,
    price: 30,
    currency: "EUR",
  },
  {
    id: "14",
    slug: "alanya-castle-damlatas-cave-beach-tour",
    image: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    title: "Alanya: Seljuk Castle, Damlatas Cave & Red Tower",
    summary:
      "Discover the medieval fortress city — cliff-top castle, ancient cave, and crimson harbour tower above turquoise Mediterranean waters.",
    location: "Alanya",
    category: "History",
    description:
      "Alanya is the Mediterranean coast's most dramatic resort town — a craggy peninsula jutting into the turquoise sea, crowned by a magnificent Seljuk castle that has dominated this stretch of coast for 800 years. Below the fortress walls, the Red Tower guards the harbour and Damlatas stalagmite cave opens beneath the cliff face. It combines archaeological treasure with one of Turkey's most popular beach destinations.",
    activities: [
      "Explore Alanya Seljuk Castle complex",
      "Tour Damlatas Cave and its stalactites",
      "Visit the Red Tower harbour fortress",
      "Swim at Cleopatra Beach",
      "Boat trip to the sea caves along the cliffs",
      "Alanya Archaeological Museum visit",
      "Cable car ride up the castle hill",
    ],
    highlights: [
      "Alanya Castle — Seljuk fortress with Mediterranean panoramas",
      "Damlatas Cave — ancient stalactite and stalagmite formations",
      "Red Tower — 13th-century octagonal harbour fortification",
    ],
    includes: ["Guide", "Cave entry", "Castle access"],
    badge: "Mediterranean Highlight",
    duration: "7 hours",
    features: ["Castle & caves", "Beach access"],
    rating: 4.6,
    reviews: 530,
    price: 33,
    currency: "EUR",
  },
  {
    id: "15",
    slug: "gaziantep-zeugma-mosaic-food-tour",
    image: "https://images.pexels.com/photos/35313541/pexels-photo-35313541.jpeg?cs=srgb&dl=pexels-aysegul-aytoren-46790226-35313541.jpg&fm=jpg",
    title: "Gaziantep: Zeugma Mosaic Museum, Spice Bazaar & Baklava Trail",
    summary:
      "Savour Turkey's food capital and explore its world-class Roman mosaic museum alongside legendary baklava workshops.",
    location: "Gaziantep",
    category: "Culture",
    description:
      "Gaziantep is widely regarded as Turkey's culinary capital, and visiting it is an absolute joy for food-lovers. Its UNESCO-recognised cuisine — over 400 distinct dishes — draws visitors from across the country. But Gaziantep is not just about food: it is also home to the Zeugma Mosaic Museum, one of the world's greatest collections of Roman mosaics, including the haunting 'Gypsy Girl' mosaic rescued from Euphrates dam waters.",
    activities: [
      "Tour Zeugma Mosaic Museum — the world's largest",
      "Baklava trail: visit legendary baklava workshops",
      "Explore Gaziantep bazaar (coppersmiths district)",
      "Visit Gaziantep Citadel and Defence Museum",
      "Taste kıymalı pide, beyran soup, and lahmacun",
      "Copper and pistachio shopping in old bazaars",
      "Evening visit to Zincirli Bedesten",
    ],
    highlights: [
      "Zeugma Mosaic Museum — UNESCO-level Roman mosaic collection",
      "Gaziantep baklava — protected geographical indication",
      "Ancient copper bazaars and Ottoman hans",
    ],
    includes: ["Museum entry", "Food tastings", "Guide"],
    badge: "Food Lover's Paradise",
    duration: "8 hours",
    features: ["Food tastings included", "Expert guide"],
    bookedText: "Popular with food lovers",
    rating: 4.9,
    reviews: 610,
    price: 42,
    currency: "EUR",
  },
  {
    id: "16",
    slug: "mardin-old-city-monastery-artisan-tour",
    image: "https://images.pexels.com/photos/35313541/pexels-photo-35313541.jpeg?cs=srgb&dl=pexels-aysegul-aytoren-46790226-35313541.jpg&fm=jpg",
    title:
      "Mardin: Honey-Stone Old City, Deyrulzafaran Monastery & Artisan Workshops",
    summary:
      "Wander Mesopotamia's most dramatic hilltop city — ancient monasteries, Syriac Christianity, and intricate limestone architecture.",
    location: "Mardin",
    category: "History",
    description:
      "Mardin is one of Turkey's most extraordinary cities — a UNESCO candidate hilltop citadel carved from honey-coloured limestone, rising high above the Mesopotamian plain. Its old city is interlaced with Syriac Christian churches, Ottoman mosques, medieval madrasas, and the workshops of silversmiths and copper-engravers who have practised their craft unchanged for centuries. Nearby Deyrulzafaran Monastery has been continuously inhabited since the 5th century.",
    activities: [
      "Walk honey-stone alleys of Mardin Old City",
      "Tour Deyrulzafaran Syriac Orthodox Monastery",
      "Visit the Grand Mosque (Ulu Cami)",
      "Explore Kasımiye and Zinciriye Madrasas",
      "Browse silver and copper artisan workshops",
      "Panoramic sunset over the Mesopotamian plain",
      "Day trip to Midyat and traditional village churches",
    ],
    highlights: [
      "Deyrulzafaran Monastery — 5th-century Syriac monastery",
      "Mardin Old City — honey-stone architecture above Mesopotamia",
      "Living Syriac artisan craft traditions",
    ],
    includes: ["Monastery entry", "Guide", "Artisan workshop visit"],
    badge: "Hidden Treasure",
    duration: "7 hours",
    features: ["Monastery visit", "Expert guide"],
    rating: 4.8,
    reviews: 280,
    price: 36,
    currency: "EUR",
  },
  {
    id: "17",
    slug: "safranbolu-ottoman-houses-cave-tour",
    image: "https://images.pexels.com/photos/35424266/pexels-photo-35424266.jpeg?cs=srgb&dl=pexels-nazmiye-kirik-1674527266-35424266.jpg&fm=jpg",
    title: "Safranbolu: UNESCO Ottoman Houses, Cinci Han & Bulak Cave",
    summary:
      "Step back into a perfectly preserved 18th-century Ottoman trading town — cobbled lanes, carved wooden mansions, and ancient caravanserai.",
    location: "Safranbolu",
    category: "Culture",
    description:
      "Safranbolu is one of the world's best-preserved Ottoman towns — a UNESCO World Heritage Site where hundreds of 18th and 19th-century timber-framed mansions line cobbled lanes exactly as they have for 300 years. Named for the saffron trade that once made it rich, Safranbolu was a crucial stop on the Silk Road. Exploring it today feels like stepping directly into the Ottoman empire: the same carved wooden lattices, stone fountains, and covered bazaar as centuries before.",
    activities: [
      "Walk cobbled lanes of Safranbolu Old Quarter",
      "Visit Kaymakamlar Mansion house museum",
      "Explore Cinci Han Ottoman caravanserai",
      "Tour Bulak Mencilis stalactite cave",
      "See the Grand Mosque and Clock Tower",
      "Taste Turkish delight and saffron sweets",
      "Sunset views from Hıdırlık Hill",
    ],
    highlights: [
      "UNESCO World Heritage Ottoman old town",
      "Kaymakamlar Mansion — finest of 1,000+ heritage houses",
      "Cinci Han — 17th-century caravanserai still in use",
    ],
    includes: ["Museum entry", "Guide", "Cave access"],
    badge: "UNESCO Heritage",
    duration: "6 hours",
    features: ["UNESCO site", "Heritage architecture"],
    rating: 4.7,
    reviews: 340,
    price: 28,
    currency: "EUR",
  },
  {
    id: "18",
    slug: "istanbul-grand-bazaar-spice-market-food-tour",
    image: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    title: "Istanbul: Grand Bazaar, Spice Market & Street Food Walking Tour",
    summary:
      "Taste your way through Istanbul's legendary covered bazaars — simit, baklava, Turkish delight, and fresh pomegranate juice.",
    location: "Istanbul",
    category: "Food & Culinary",
    description:
      "The Grand Bazaar is one of the world's oldest and largest covered markets — 61 streets, 4,000 shops, and centuries of mercantile history under one roof. This food and market tour peels back the tourist surface to reveal the authentic trading world inside: the tea boys weaving through crowds, the spice mounds of the Egyptian Bazaar, and the local eateries where Istanbul residents have lunched for generations.",
    activities: [
      "Guided walk through Grand Bazaar's 61 covered streets",
      "Tour of the Spice (Egyptian) Bazaar",
      "Street food tasting — simit, börek, dürüm",
      "Turkish tea ceremony at a traditional çayhane",
      "Taste freshly ground Turkish coffee",
      "Baklava and Turkish delight workshop",
      "Browse authentic carpet and ceramic stalls",
    ],
    highlights: [
      "Grand Bazaar — 500-year-old covered market maze",
      "Egyptian Spice Bazaar — vivid mounds of spices and dried fruits",
      "Authentic street food stops away from tourist traps",
    ],
    includes: ["Guide", "Food tastings", "Tea and coffee"],
    badge: "Top Food Experience",
    duration: "3.5 hours",
    features: ["Food tastings included", "Small group"],
    bookedText: "Booked 65 times today",
    rating: 4.9,
    reviews: 2100,
    price: 38,
    currency: "EUR",
    highlightedReviews: [
      {
        reviewer: "Emma",
        country: "United Kingdom",
        date: "February 20, 2026",
        rating: 5,
        text: "The best food tour I've ever done. Our guide knew every vendor personally and took us to places we'd never have found alone. The börek from that tiny shop off the main corridor was extraordinary.",
        verified: true,
      },
      {
        reviewer: "Hiroshi",
        country: "Japan",
        date: "January 15, 2026",
        rating: 5,
        text: "Incredible sensory experience. We tasted at least 15 different foods and learned so much about Ottoman culinary history. The spice market alone was worth the price.",
        verified: true,
      },
    ],
  },
  {
    id: "19",
    slug: "cappadocia-atv-valleys-sunset-tour",
    image: "https://images.pexels.com/photos/34012271/pexels-photo-34012271.jpeg?cs=srgb&dl=pexels-photo4artt-34012271.jpg&fm=jpg",
    title: "Cappadocia: ATV Quad Bike Tour Through Rose & Red Valleys",
    summary:
      "Race through fairy chimneys and ochre canyons on an ATV as the Cappadocian sunset turns the valleys gold.",
    location: "Cappadocia",
    category: "Adventure",
    description:
      "While the balloon flight gives you Cappadocia from the sky, an ATV tour puts you inside the landscape — weaving between towering fairy chimneys, down into vineyard-filled valleys, and along ancient caravan trails carved through the volcanic rock. The Rose and Red Valleys at sunset are among the most photogenic scenes in Turkey, and riding through them as the light turns golden is an experience of pure freedom.",
    activities: [
      "ATV quad ride through Rose Valley at sunset",
      "Explore Red Valley rock formations up close",
      "Stop at panoramic viewpoints over Göreme",
      "Visit ancient cave churches carved into cliffs",
      "Ride through vineyard trails and orchards",
      "Photography stops at best sunset spots",
      "Optional upgrade to private ATV",
    ],
    highlights: [
      "Rose Valley at sunset — most photogenic in Cappadocia",
      "ATV riding through fairy chimneys and canyons",
      "Ancient cave churches and Byzantine rock carvings",
    ],
    includes: ["ATV rental", "Helmet and safety gear", "Guide"],
    badge: "Adrenaline Pick",
    duration: "2.5 hours",
    features: ["ATV included", "Sunset timing"],
    bookedText: "Booked 40 times today",
    rating: 4.8,
    reviews: 870,
    price: 55,
    currency: "EUR",
  },
  {
    id: "20",
    slug: "pamukkale-cleopatra-pool-swim-tour",
    image: "https://images.pexels.com/photos/34215958/pexels-photo-34215958.jpeg?cs=srgb&dl=pexels-missptr-34215958.jpg&fm=jpg",
    title: "Pamukkale: Swim in Cleopatra's Ancient Pool & Travertine Terraces",
    summary:
      "Bathe in the 2,000-year-old thermal pool where Cleopatra is said to have swum, among submerged Roman marble columns.",
    location: "Pamukkale",
    category: "Relaxation",
    description:
      "Cleopatra's Antique Pool is one of the most extraordinary bathing experiences in the world: a warm, mineral-rich thermal pool in which actual Roman columns lie submerged on the bottom, exactly where an earthquake sent them centuries ago. Swimming here, with the white travertine hillside above and ancient marble beneath your feet, is a sublime combination of nature, history, and pure sensory pleasure.",
    activities: [
      "Swim in Cleopatra's Antique Pool among sunken columns",
      "Wade through the white travertine thermal cascades",
      "Explore Hierapolis ancient theatre and necropolis",
      "Visit the Hierapolis Archaeological Museum",
      "Sunset walk on the upper terraces",
      "Photograph the iconic cotton-castle terraces",
      "Optional traditional Turkish bath (hammam)",
    ],
    highlights: [
      "Cleopatra's Pool — swim among 2,000-year-old Roman columns",
      "White travertine terraces — UNESCO Natural Wonder",
      "Hierapolis Greco-Roman ruins directly above the pools",
    ],
    includes: ["Pool entry", "Terrace access", "Guide"],
    badge: "Bucket List",
    duration: "7 hours",
    features: ["Swimming included", "UNESCO site"],
    rating: 4.8,
    reviews: 1430,
    price: 62,
    currency: "EUR",
    highlightedReviews: [
      {
        reviewer: "Zoe",
        country: "Australia",
        date: "March 2, 2026",
        rating: 5,
        text: "Swimming in Cleopatra's Pool was surreal — the warm mineral water, ancient columns under your feet, and the white terraces behind you. Completely unlike anything else I've experienced anywhere.",
        verified: true,
      },
    ],
  },
  {
    id: "21",
    slug: "istanbul-turkish-cooking-class-bosphorus",
    image: "https://images.pexels.com/photos/31661448/pexels-photo-31661448.jpeg?cs=srgb&dl=pexels-pelin-2937827-31661448.jpg&fm=jpg",
    title:
      "Istanbul: Turkish Cooking Class with Market Visit & Bosphorus Lunch",
    summary:
      "Learn to cook mezes, kebabs, and baklava with a professional chef in an Istanbul kitchen, then dine beside the Bosphorus.",
    location: "Istanbul",
    category: "Food & Culinary",
    description:
      "Turkish cuisine is one of the world's great culinary traditions — and Istanbul is its capital. This hands-on cooking class begins at the morning market where you select fresh produce with your chef, then moves to a traditional kitchen where you learn to prepare a full spread of Turkish dishes from scratch. The session ends with all of you sitting down together to eat what you cooked, with a Bosphorus view.",
    activities: [
      "Morning market tour to select fresh ingredients",
      "Hands-on cooking class — mezes, main, dessert",
      "Learn to make börek, dolma, and baklava",
      "Sit-down group meal with Bosphorus view",
      "Turkish tea and coffee tasting",
      "Recipe cards and technique notes to take home",
      "Optional private class upgrade",
    ],
    highlights: [
      "Professional chef-led hands-on cooking session",
      "Fresh Bosphorus-side dining after cooking",
      "Market visit and ingredient selection",
    ],
    includes: ["Market tour", "All ingredients", "Full meal"],
    badge: "Highly Rated",
    duration: "4 hours",
    features: ["Hands-on cooking", "Meal included"],
    bookedText: "Booked 28 times today",
    rating: 4.9,
    reviews: 760,
    price: 70,
    currency: "EUR",
  },
  {
    id: "22",
    slug: "cappadocia-underground-city-hike-tour",
    image: "https://images.pexels.com/photos/34012271/pexels-photo-34012271.jpeg?cs=srgb&dl=pexels-photo4artt-34012271.jpg&fm=jpg",
    title: "Cappadocia: Derinkuyu Underground City & Ihlara Valley Hike",
    summary:
      "Descend into an 8-level underground city that sheltered 20,000 people, then hike a dramatic canyon carved by a river over millennia.",
    location: "Cappadocia",
    category: "Adventure",
    description:
      "Derinkuyu is the most astonishing feat of underground architecture in the ancient world — a subterranean city drilled 85 metres into the volcanic rock, with 18 levels capable of sheltering an entire population during invasions. Nearby, the Ihlara Valley is a 14 km canyon carved by the Melendiz River, its sheer walls dotted with Byzantine cave churches and its floor a lush, shaded hiking trail.",
    activities: [
      "Guided descent into Derinkuyu 8-level underground city",
      "Explore tunnels, churches, wine cellars, and stables",
      "Hike 6 km of Ihlara Valley canyon floor",
      "Visit Byzantine cave churches in canyon walls",
      "Lunch at a riverside restaurant in the valley",
      "See Selime Monastery carved into cliff faces",
      "Photography at canyon viewpoints",
    ],
    highlights: [
      "Derinkuyu — 8-level underground city for 20,000 people",
      "Ihlara Valley — stunning river canyon with cave churches",
      "Selime Monastery — largest cave monastery in Turkey",
    ],
    includes: ["Underground city entry", "Guide", "Valley hike", "Lunch"],
    badge: "Adventure Pick",
    duration: "10 hours",
    features: ["Lunch included", "Underground + hiking"],
    rating: 4.7,
    reviews: 640,
    price: 65,
    currency: "EUR",
  },
  {
    id: "23",
    slug: "bodrum-sunset-catamaran-cruise",
    image: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    title: "Bodrum: Sunset Catamaran Cruise with Dinner & Live Music",
    summary:
      "Sail the Aegean on a sleek catamaran as the sun drops behind the Bodrum peninsula — dinner, open bar, and live Turkish music.",
    location: "Bodrum",
    category: "Adventure",
    description:
      "This evening catamaran cruise is Bodrum at its most seductive: gliding across the deep Aegean as the light turns amber and rose behind the castle on the hill, a glass of cold rakı in hand, the sound of a saz (Turkish lute) drifting across the water. The dinner served on board is a genuine Turkish feast — fresh meze, grilled fish, and seasonal vegetables — rather than the reheated buffet typical of tourist cruises.",
    activities: [
      "Sunset catamaran sail around Bodrum peninsula",
      "Swimming stops at hidden coves",
      "Three-course Turkish dinner on board",
      "Open bar (wine, beer, soft drinks)",
      "Live saz and Turkish folk music performance",
      "Visit to Bodrum harbour at dusk",
      "Dancing on deck under the stars",
    ],
    highlights: [
      "Sunset sail past Bodrum Castle",
      "Fresh Turkish dinner and open bar on board",
      "Live Turkish folk music with saz player",
    ],
    includes: ["Dinner", "Open bar", "Live music", "Transfer"],
    badge: "Romantic Pick",
    duration: "4 hours",
    features: ["Dinner included", "Open bar"],
    bookedText: "Booked 22 times today",
    rating: 4.8,
    reviews: 490,
    price: 58,
    currency: "EUR",
  },
  {
    id: "24",
    slug: "ankara-turkish-bath-hammam-experience",
    image: "https://images.pexels.com/photos/19197366/pexels-photo-19197366.jpeg?cs=srgb&dl=pexels-turuncu-sakal-523826045-19197366.jpg&fm=jpg",
    title: "Ankara: Authentic Ottoman Hammam Experience at Karacabey Bath",
    summary:
      "Surrender to a centuries-old bathing ritual — marble slabs, kese scrub, foam massage, and total relaxation in a 16th-century hammam.",
    location: "Ankara",
    category: "Relaxation",
    description:
      "The Ottoman hammam is one of the world's great bathing traditions — a ritual of heat, water, and touch that has been practised in these marble halls for 500 years. The Karacabey hammam in Ankara dates to the 16th century and operates exactly as it always has: you enter the tepidarium, move to the central marble slab heated from below, are scrubbed with a kese mitt to remove dead skin, then massaged with fragrant soap foam by experienced tellaks.",
    activities: [
      "Full hammam ritual on heated marble slab",
      "Kese (exfoliation mitt) full-body scrub",
      "Traditional foam soap massage",
      "Relaxation in cold and warm bath areas",
      "Herbal oil treatment add-on",
      "Historical hammam architecture tour",
      "Traditional tea served after session",
    ],
    highlights: [
      "16th-century Ottoman hammam in active use",
      "Full kese scrub and foam massage by expert tellaks",
      "Genuine local experience — not a tourist spa",
    ],
    includes: ["Hammam entry", "Towel and soap", "Tea"],
    badge: "Wellness Must-Try",
    duration: "2 hours",
    features: ["Hammam scrub included", "Relaxation"],
    rating: 4.7,
    reviews: 320,
    price: 35,
    currency: "EUR",
  },
  {
    id: "25",
    slug: "istanbul-princes-islands-bike-day-trip",
    image: "https://images.pexels.com/photos/33985970/pexels-photo-33985970.jpeg?cs=srgb&dl=pexels-barkali-340353352-33985970.jpg&fm=jpg",
    title: "Istanbul: Büyükada Princes' Island Bike Ride & Ferry Day Trip",
    summary:
      "Escape the city on a ferry to the car-free Princes' Islands — rent a bike, circle the island, and swim in the Marmara Sea.",
    location: "Istanbul",
    category: "Adventure",
    description:
      "Büyükada is one of Istanbul's best-kept secrets — the largest of the Princes' Islands, a car-free enclave in the Sea of Marmara where the only transport is bicycle or horse-drawn carriage. Victorian-era wooden mansions line quiet lanes shaded by pine trees, and the sea air carries none of the city's noise or exhaust. A ferry from Eminönü deposits you in another world entirely — relaxed, leafy, and blissfully unhurried.",
    activities: [
      "Ferry ride from Istanbul across the sea",
      "Bike rental and guided island circuit",
      "Swim at the island's rocky southern coves",
      "Lunch at a seafront fish restaurant",
      "Visit Aya Yorgi Church hilltop monastery",
      "Browse the handmade craft shops in town",
      "Return sunset ferry with Bosphorus views",
    ],
    highlights: [
      "Car-free island — only bikes and horse carriages",
      "Victorian wooden mansions in pine forests",
      "Swimming in the clean Sea of Marmara",
    ],
    includes: ["Ferry tickets", "Bike rental", "Guide"],
    badge: "Day Escape",
    duration: "8 hours",
    features: ["Ferry included", "Bike rental included"],
    rating: 4.7,
    reviews: 810,
    price: 44,
    currency: "EUR",
  },
  {
    id: "26",
    slug: "antalya-perge-aspendos-ruins-day-tour",
    image: "https://images.pexels.com/photos/31914566/pexels-photo-31914566.jpeg?cs=srgb&dl=pexels-eren-31914566.jpg&fm=jpg",
    title: "Antalya: Perge Ruins, Aspendos Roman Theatre & Side Ancient City",
    summary:
      "A full-day archaeological journey through three of the Mediterranean coast's greatest Greco-Roman cities.",
    location: "Antalya",
    category: "History",
    description:
      "The Pamphylian plain east of Antalya was once among the most densely urbanised regions of the Roman Empire. Three cities in particular stand out: Perge, with its magnificent colonnaded street and stadium; Aspendos, home to the best-preserved Roman theatre in the world (still used for live performances today); and Side, a beautiful coastal ruin whose temples overlook the turquoise sea.",
    activities: [
      "Explore Perge ancient city colonnaded street and baths",
      "Tour Aspendos Roman theatre — best preserved on earth",
      "Walk the ruins of Side beside the Mediterranean",
      "Side Archaeological Museum treasures",
      "Photo stop at Apollo Temple at the sea",
      "Traditional lunch in a Side restaurant",
      "Expert archaeologist commentary throughout",
    ],
    highlights: [
      "Aspendos Theatre — best preserved Roman theatre in the world",
      "Perge — magnificent colonnaded Roman city",
      "Side — coastal ruins with Apollo Temple at the sea",
    ],
    includes: ["Entry tickets", "Archaeologist guide", "Lunch", "Transport"],
    badge: "Archaeology Special",
    duration: "10 hours",
    features: ["Lunch included", "Expert archaeologist"],
    rating: 4.8,
    reviews: 720,
    price: 68,
    currency: "EUR",
  },
  {
    id: "27",
    slug: "trabzon-tea-plantation-highlands-tour",
    image: "https://images.pexels.com/photos/35165112/pexels-photo-35165112.jpeg?cs=srgb&dl=pexels-kadernamuslu-35165112.jpg&fm=jpg",
    title:
      "Trabzon: Black Sea Tea Plantations, Rize & Ayder Plateau Hot Springs",
    summary:
      "Drive through emerald tea terraces to Turkey's tea capital Rize, then soak in a natural hot spring on a misty highland plateau.",
    location: "Trabzon",
    category: "Nature",
    description:
      "The eastern Black Sea coast is Turkey's tea country — a landscape of steep green hillsides cascading with terraced tea gardens that produce the nation's most beloved drink. Rize is the undisputed capital of Turkish tea culture, and visiting its plantations is a deeply pleasant surprise: lush, misty, and utterly unlike the arid landscapes most visitors associate with Turkey. Above the coast, the Ayder plateau sits in a natural amphitheatre of peaks, with natural hot springs flowing year-round.",
    activities: [
      "Tour Rize tea plantations and learn harvesting process",
      "Tea tasting and çay factory visit",
      "Scenic mountain drive to Ayder plateau",
      "Soak in natural Ayder hot springs",
      "Hike through alpine meadows and waterfalls",
      "Traditional Black Sea breakfast with local cheeses",
      "Visit Hemşin village and local lifestyle",
    ],
    highlights: [
      "Rize tea plantations — Turkey's tea heartland",
      "Ayder plateau natural hot springs at 1,350m altitude",
      "Pure Black Sea highland landscapes and waterfalls",
    ],
    includes: ["Tea tastings", "Hot spring entry", "Breakfast", "Transport"],
    badge: "Nature Escape",
    duration: "11 hours",
    features: ["Breakfast included", "Hot springs"],
    rating: 4.7,
    reviews: 390,
    price: 48,
    currency: "EUR",
  },
  {
    id: "28",
    slug: "istanbul-nightlife-rooftop-bar-tour",
    image: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    title: "Istanbul: Rooftop Bar Crawl — Sultanahmet to Beyoğlu by Night",
    summary:
      "See Istanbul from above after dark — three iconic rooftop bars with Bosphorus and Golden Horn views, led by a local nightlife guide.",
    location: "Istanbul",
    category: "Culture",
    description:
      "Istanbul by night is one of the great urban experiences on earth — the Bosphorus lit up, the minarets illuminated, and the Golden Horn shimmering between two continents. This after-dark rooftop tour takes small groups to three of the city's finest elevated bars and viewpoints, from the historic peninsula to Beyoğlu's vibrant streets, with a local guide providing context on everything from Ottoman architecture to the city's thriving contemporary arts scene.",
    activities: [
      "Drinks at a Sultanahmet rooftop with Blue Mosque views",
      "Cross the Galata Bridge at night on foot",
      "Visit Galata Tower neighbourhood bars",
      "Beyoğlu rooftop with 360° Bosphorus panorama",
      "Street food stop — midye dolma and kokoreç",
      "Drinks at a jazz bar in Karaköy",
      "Late stroll through Istiklal Avenue",
    ],
    highlights: [
      "Three rooftop venues with Bosphorus and old city views",
      "Galata Bridge night crossing with guide",
      "Beyoğlu contemporary bar and music scene",
    ],
    includes: [
      "1 drink per venue included",
      "Guide",
      "Transport between venues",
    ],
    badge: "Evening Experience",
    duration: "4 hours",
    features: ["Drinks included", "Small group"],
    rating: 4.8,
    reviews: 560,
    price: 48,
    currency: "EUR",
  },
  {
    id: "29",
    slug: "aegean-fethiye-blue-lagoon-paragliding",
    image: "https://images.pexels.com/photos/34455610/pexels-photo-34455610.jpeg?cs=srgb&dl=pexels-fatih-celik-2153210214-34455610.jpg&fm=jpg",
    title:
      "Fethiye: Tandem Paraglide from Babadağ Mountain over the Blue Lagoon",
    summary:
      "Take off from 1,960m and soar above Ölüdeniz's legendary Blue Lagoon — the world's most photographed paragliding site.",
    location: "Fethiye",
    category: "Adventure",
    description:
      "Babadağ is the most famous paragliding mountain in the world, and the reason is immediately obvious when you run off the launch ramp: below you spreads the Ölüdeniz Blue Lagoon, an impossible turquoise comma of protected water framed by pine-green cliffs. The tandem flight with a certified pilot lasts 30–45 minutes, during which you soar at 1,960 metres before spiralling gradually down to the beach below — the most exhilarating 40 minutes in Turkey.",
    activities: [
      "Tandem paraglide from Babadağ summit (1,960m)",
      "Soar above Ölüdeniz Blue Lagoon",
      "Transfer to Babadağ mountain by 4WD",
      "Full safety briefing and equipment fitting",
      "GoPro video and photo package",
      "Swim at Ölüdeniz beach after landing",
      "Boat trip to the Blue Lagoon enclosure",
    ],
    highlights: [
      "World-famous Babadağ — premier paragliding mountain globally",
      "Ölüdeniz Blue Lagoon — voted most scenic beach in Turkey",
      "30-45 min flight with certified tandem pilot",
    ],
    includes: ["Tandem pilot", "Equipment", "Mountain transfer", "Video"],
    badge: "Ultimate Thrill",
    duration: "5 hours",
    features: ["Video included", "World-class site"],
    bookedText: "Booked 55 times today",
    rating: 4.9,
    reviews: 1890,
    price: 95,
    currency: "EUR",
    highlightedReviews: [
      {
        reviewer: "Thomas",
        country: "Germany",
        date: "February 28, 2026",
        rating: 5,
        text: "The most frightening and the most beautiful thing I have ever done. I screamed at take-off and cried from happiness 10 minutes later looking down at that impossible blue water. Book it immediately.",
        verified: true,
      },
      {
        reviewer: "Priya",
        country: "India",
        date: "January 30, 2026",
        rating: 5,
        text: "I was terrified beforehand but my pilot was so calm and professional that the fear vanished completely. The view of the Blue Lagoon from above is something photographs simply cannot capture.",
        verified: true,
      },
    ],
  },
  {
    id: "30",
    slug: "istanbul-princess-topkapi-harem-guided-tour",
    image: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    title: "Istanbul: Topkapi Palace Harem, Treasury & Imperial Pavilions",
    summary:
      "Unlock the secret rooms of the Ottoman world — the Harem, the Diamond-studded Treasury, and the Sacred Relics Chamber.",
    location: "Istanbul",
    category: "Culture",
    description:
      "Topkapi Palace was the administrative and residential heart of the Ottoman Empire for 400 years, and its innermost sections — the Harem, the Treasury, and the Sacred Relics Chamber — are the most fascinating and least understood by visitors exploring independently. A specialist guide transforms these rooms from a parade of objects into a living world: the Sultan's bedroom politics, the Harem hierarchy, the 86-carat Spoonmaker's Diamond, and the cloak of the Prophet Muhammad.",
    activities: [
      "Private access to the Harem with specialist guide",
      "Treasury visit — Spoonmaker's Diamond and Topkapi Dagger",
      "Sacred Relics Chamber — cloak of the Prophet",
      "Imperial Council Chamber (Divan) and kitchens",
      "Fourth Courtyard garden and Golden Horn views",
      "Baghdad Kiosk and Circumcision Room details",
      "Q&A with specialist Ottoman historian guide",
    ],
    highlights: [
      "Topkapi Harem — 400-room private palace within a palace",
      "Treasury — 86-carat Spoonmaker's Diamond and jewelled dagger",
      "Sacred Relics — personal belongings of the Prophet Muhammad",
    ],
    includes: ["Skip-the-line tickets", "Harem ticket", "Specialist guide"],
    badge: "Deep Dive",
    duration: "4 hours",
    features: ["Harem access", "Skip the line"],
    rating: 4.9,
    reviews: 1340,
    price: 72,
    currency: "EUR",
  },
  {
    id: "31",
    slug: "izmir-cesme-beach-wine-day-tour",
    image: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    title: "Izmir: Çeşme Peninsula Beach Day & Aegean Wine Tasting",
    summary:
      "Sun-drenched beaches, ancient Genoese castle, and the crisp white wines of the Urla wine route on the Aegean coast.",
    location: "Izmir",
    category: "Relaxation",
    description:
      "The Çeşme Peninsula is Izmir's playground — a sliver of land surrounded by the clearest Aegean waters in Turkey, watched over by a 14th-century Genoese castle and blessed with consistent summer winds that make it the country's windsurfing capital. The Urla wine route on the return journey reveals a thriving boutique wine scene producing some of Turkey's finest whites from indigenous grape varieties.",
    activities: [
      "Beach day at Ilıca or Çeşme main beach",
      "Tour Çeşme Genoese castle and museum",
      "Wild swimming at Ayvalık natural springs cove",
      "Urla wine route — two boutique winery visits",
      "Tasting of local Bornova misketi white wine",
      "Fresh seafood lunch at a harbour restaurant",
      "Browse Çeşme waterfront promenade",
    ],
    highlights: [
      "Çeşme — clearest Aegean swimming waters in Turkey",
      "Genoese Castle — 14th-century fortress over the harbour",
      "Urla wine route — Turkey's emerging fine wine region",
    ],
    includes: ["Wine tastings", "Lunch", "Transport", "Castle entry"],
    badge: "Relax & Taste",
    duration: "9 hours",
    features: ["Wine tastings included", "Beach access"],
    rating: 4.7,
    reviews: 415,
    price: 52,
    currency: "EUR",
  },
  {
    id: "32",
    slug: "konya-salt-lake-sultan-marshes-nature-tour",
    image: "https://images.pexels.com/photos/34215958/pexels-photo-34215958.jpeg?cs=srgb&dl=pexels-missptr-34215958.jpg&fm=jpg",
    title: "Konya: Tuz Gölü Salt Lake & Sultan Marshes Bird Watching Tour",
    summary:
      "Walk across a boundless white salt flat that mirrors the sky, then watch thousands of flamingos in one of Turkey's greatest wildlife spectacles.",
    location: "Konya",
    category: "Nature",
    description:
      "Tuz Gölü (Salt Lake) is Turkey's second-largest lake and one of the world's largest salt flats — a blinding white expanse that stretches to every horizon, with a shallow brine layer that creates perfect mirror reflections of clouds and sky. Just south, the Sultan Marshes are a Ramsar-protected wetland and the breeding ground for over 300 bird species, including enormous flocks of greater flamingos that turn the shallow waters pink.",
    activities: [
      "Walk across Tuz Gölü salt flat at sunrise",
      "Photography of mirror-reflection sky scenes",
      "Guided bird watching at Sultan Sazlığı Marshes",
      "Flamingo colony observation from hides",
      "Spot pelicans, herons, and storks in season",
      "Visit a local salt production facility",
      "Picnic lunch on the salt flat edge",
    ],
    highlights: [
      "Tuz Gölü — vast salt flat with sky-mirror reflections",
      "Sultan Marshes — flamingo flocks up to 10,000 birds",
      "300+ bird species in Ramsar wetland reserve",
    ],
    includes: ["Transport", "Guide", "Binoculars", "Picnic lunch"],
    badge: "Wildlife Wonder",
    duration: "10 hours",
    features: ["Bird watching", "Salt flat walking"],
    rating: 4.6,
    reviews: 240,
    price: 40,
    currency: "EUR",
  },
]

export function getProductById(id: string) {
  return products.find(product => product.id === id) ?? null
}

export function formatPrice(product: Product) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: product.currency,
    maximumFractionDigits: 0,
  }).format(product.price)
}

export const filters = [
  "AI Itineraries",
  "Cultural Tours",
  "Historical Sites",
  "Adventure",
  "Food & Culinary",
  "Relaxation",
  "Cruises",
  "Family Friendly",
  "Budget Friendly",
]
