export interface ProductImageAttribution {
  location: string
  sourceName: string
  sourcePage: string
  imageUrl: string
  licenseNote: string
}

// These entries document the curated replacements for the old picsum placeholders.
// Source pages were researched from Pexels and the browser now loads the CDN image URLs directly.
export const productImageAttributions: Record<string, ProductImageAttribution> = {
  "cappadocia-sunrise-balloon-flight": {
    location: "Cappadocia",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/aerial-view-of-famous-cappadocia-landscape-34012271/",
    imageUrl: "https://images.pexels.com/photos/34012271/pexels-photo-34012271.jpeg?cs=srgb&dl=pexels-photo4artt-34012271.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "istanbul-hagia-sophia-blue-mosque-topkapi-tour": {
    location: "Istanbul",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/istanbul-skyline-featuring-hagia-sophia-at-dusk-35582896/",
    imageUrl: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "ephesus-small-group-tour-kusadasi-izmir": {
    location: "Ephesus",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/celsus-library-ruins-in-ephesus-turkey-36122307/",
    imageUrl: "https://images.pexels.com/photos/36122307/pexels-photo-36122307.jpeg?cs=srgb&dl=pexels-hobiphotography-36122307.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "pamukkale-hierapolis-full-day-tour": {
    location: "Pamukkale",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/stunning-travertine-terraces-of-pamukkale-34215958/",
    imageUrl: "https://images.pexels.com/photos/34215958/pexels-photo-34215958.jpeg?cs=srgb&dl=pexels-missptr-34215958.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "bodrum-blue-voyage-gulet-cruise": {
    location: "Bodrum",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/bodrum-coastal-view-with-turkish-flag-at-dusk-33822707/",
    imageUrl: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "antalya-old-town-waterfall-tour": {
    location: "Antalya",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/majestic-waterfall-in-antalya-s-lush-forest-31914566/",
    imageUrl: "https://images.pexels.com/photos/31914566/pexels-photo-31914566.jpeg?cs=srgb&dl=pexels-eren-31914566.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "bursa-grand-mosque-silk-market-tour": {
    location: "Bursa",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/mevlana-museum-in-konya-19792501/",
    imageUrl: "https://images.pexels.com/photos/19792501/pexels-photo-19792501.jpeg?cs=srgb&dl=pexels-zeynep-gonul-kocak-896406907-19792501.jpg&fm=jpg",
    licenseNote: "Fallback architecture image from Pexels while a Bursa-specific photo is curated.",
  },
  "ankara-anitkabir-museum-anatolian-civilizations": {
    location: "Ankara",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/anitkabir-ataturk-mausoleum-in-ankara-19197366/",
    imageUrl: "https://images.pexels.com/photos/19197366/pexels-photo-19197366.jpeg?cs=srgb&dl=pexels-turuncu-sakal-523826045-19197366.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "trabzon-sumela-monastery-black-sea-tour": {
    location: "Trabzon / Rize",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/scenic-tea-plantations-in-turkish-countryside-35165112/",
    imageUrl: "https://images.pexels.com/photos/35165112/pexels-photo-35165112.jpeg?cs=srgb&dl=pexels-kadernamuslu-35165112.jpg&fm=jpg",
    licenseNote: "Fallback Black Sea region image from Rize tea hills while a Sumela-specific photo is curated.",
  },
  "konya-mevlana-museum-whirling-dervish": {
    location: "Konya",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/mevlana-museum-in-konya-19792501/",
    imageUrl: "https://images.pexels.com/photos/19792501/pexels-photo-19792501.jpeg?cs=srgb&dl=pexels-zeynep-gonul-kocak-896406907-19792501.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "troy-ancient-ruins-canakkale-tour": {
    location: "Canakkale",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/celsus-library-ruins-in-ephesus-turkey-36122307/",
    imageUrl: "https://images.pexels.com/photos/36122307/pexels-photo-36122307.jpeg?cs=srgb&dl=pexels-hobiphotography-36122307.jpg&fm=jpg",
    licenseNote: "Fallback ruins image from western Turkey while a Troy-specific photo is curated.",
  },
  "istanbul-bosphorus-cruise-two-continents": {
    location: "Istanbul",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/scenic-view-of-bosphorus-with-boats-on-water-31661448/",
    imageUrl: "https://images.pexels.com/photos/31661448/pexels-photo-31661448.jpeg?cs=srgb&dl=pexels-pelin-2937827-31661448.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "izmir-agora-kordon-winery-tour": {
    location: "Izmir",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/celsus-library-ruins-in-ephesus-turkey-36122307/",
    imageUrl: "https://images.pexels.com/photos/36122307/pexels-photo-36122307.jpeg?cs=srgb&dl=pexels-hobiphotography-36122307.jpg&fm=jpg",
    licenseNote: "Fallback Aegean archaeology image from nearby Ephesus while an Izmir-specific photo is curated.",
  },
  "alanya-castle-damlatas-cave-beach-tour": {
    location: "Alanya",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/bodrum-coastal-view-with-turkish-flag-at-dusk-33822707/",
    imageUrl: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    licenseNote: "Fallback Turkish coast image while an Alanya-specific photo is curated.",
  },
  "gaziantep-zeugma-mosaic-food-tour": {
    location: "Gaziantep",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/historic-mardin-street-with-statue-and-architecture-35313541/",
    imageUrl: "https://images.pexels.com/photos/35313541/pexels-photo-35313541.jpeg?cs=srgb&dl=pexels-aysegul-aytoren-46790226-35313541.jpg&fm=jpg",
    licenseNote: "Fallback southeast Turkey city image while a Gaziantep-specific photo is curated.",
  },
  "mardin-old-city-monastery-artisan-tour": {
    location: "Mardin",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/historic-mardin-street-with-statue-and-architecture-35313541/",
    imageUrl: "https://images.pexels.com/photos/35313541/pexels-photo-35313541.jpeg?cs=srgb&dl=pexels-aysegul-aytoren-46790226-35313541.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "safranbolu-ottoman-houses-cave-tour": {
    location: "Safranbolu",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/safranbolu-historic-cityscape-with-ottoman-architecture-35424266/",
    imageUrl: "https://images.pexels.com/photos/35424266/pexels-photo-35424266.jpeg?cs=srgb&dl=pexels-nazmiye-kirik-1674527266-35424266.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "istanbul-grand-bazaar-spice-market-food-tour": {
    location: "Istanbul",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/istanbul-skyline-featuring-hagia-sophia-at-dusk-35582896/",
    imageUrl: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    licenseNote: "Fallback Istanbul city image while a bazaar-specific photo is curated.",
  },
  "cappadocia-atv-valleys-sunset-tour": {
    location: "Cappadocia",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/aerial-view-of-famous-cappadocia-landscape-34012271/",
    imageUrl: "https://images.pexels.com/photos/34012271/pexels-photo-34012271.jpeg?cs=srgb&dl=pexels-photo4artt-34012271.jpg&fm=jpg",
    licenseNote: "Fallback Cappadocia landscape image while an ATV-specific photo is curated.",
  },
  "pamukkale-cleopatra-pool-swim-tour": {
    location: "Pamukkale",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/stunning-travertine-terraces-of-pamukkale-34215958/",
    imageUrl: "https://images.pexels.com/photos/34215958/pexels-photo-34215958.jpeg?cs=srgb&dl=pexels-missptr-34215958.jpg&fm=jpg",
    licenseNote: "Fallback Pamukkale terraces image while a Cleopatra Pool-specific photo is curated.",
  },
  "istanbul-turkish-cooking-class-bosphorus": {
    location: "Istanbul",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/scenic-view-of-bosphorus-with-boats-on-water-31661448/",
    imageUrl: "https://images.pexels.com/photos/31661448/pexels-photo-31661448.jpeg?cs=srgb&dl=pexels-pelin-2937827-31661448.jpg&fm=jpg",
    licenseNote: "Fallback Istanbul Bosphorus image while a cooking-class photo is curated.",
  },
  "cappadocia-underground-city-hike-tour": {
    location: "Cappadocia",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/aerial-view-of-famous-cappadocia-landscape-34012271/",
    imageUrl: "https://images.pexels.com/photos/34012271/pexels-photo-34012271.jpeg?cs=srgb&dl=pexels-photo4artt-34012271.jpg&fm=jpg",
    licenseNote: "Fallback Cappadocia landscape image while an underground-city photo is curated.",
  },
  "bodrum-sunset-catamaran-cruise": {
    location: "Bodrum",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/bodrum-coastal-view-with-turkish-flag-at-dusk-33822707/",
    imageUrl: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    licenseNote: "Pexels coastal photo suitable for the Bodrum cruise card.",
  },
  "ankara-turkish-bath-hammam-experience": {
    location: "Ankara",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/anitkabir-ataturk-mausoleum-in-ankara-19197366/",
    imageUrl: "https://images.pexels.com/photos/19197366/pexels-photo-19197366.jpeg?cs=srgb&dl=pexels-turuncu-sakal-523826045-19197366.jpg&fm=jpg",
    licenseNote: "Fallback Ankara landmark image while a hammam-specific photo is curated.",
  },
  "istanbul-princes-islands-bike-day-trip": {
    location: "Buyukada",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/charming-street-in-buyukada-istanbul-33985970/",
    imageUrl: "https://images.pexels.com/photos/33985970/pexels-photo-33985970.jpeg?cs=srgb&dl=pexels-barkali-340353352-33985970.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "antalya-perge-aspendos-ruins-day-tour": {
    location: "Antalya",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/majestic-waterfall-in-antalya-s-lush-forest-31914566/",
    imageUrl: "https://images.pexels.com/photos/31914566/pexels-photo-31914566.jpeg?cs=srgb&dl=pexels-eren-31914566.jpg&fm=jpg",
    licenseNote: "Fallback Antalya destination image while a Perge/Aspendos ruins photo is curated.",
  },
  "trabzon-tea-plantation-highlands-tour": {
    location: "Rize",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/scenic-tea-plantations-in-turkish-countryside-35165112/",
    imageUrl: "https://images.pexels.com/photos/35165112/pexels-photo-35165112.jpeg?cs=srgb&dl=pexels-kadernamuslu-35165112.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "istanbul-nightlife-rooftop-bar-tour": {
    location: "Istanbul",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/istanbul-skyline-featuring-hagia-sophia-at-dusk-35582896/",
    imageUrl: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    licenseNote: "Fallback Istanbul skyline image while a nightlife-specific rooftop photo is curated.",
  },
  "aegean-fethiye-blue-lagoon-paragliding": {
    location: "Fethiye",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/paragliding-adventure-in-fethiye-turkiye-skies-34455610/",
    imageUrl: "https://images.pexels.com/photos/34455610/pexels-photo-34455610.jpeg?cs=srgb&dl=pexels-fatih-celik-2153210214-34455610.jpg&fm=jpg",
    licenseNote: "Pexels free stock photo; verify usage requirements if you need printed attribution.",
  },
  "istanbul-princess-topkapi-harem-guided-tour": {
    location: "Istanbul",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/istanbul-skyline-featuring-hagia-sophia-at-dusk-35582896/",
    imageUrl: "https://images.pexels.com/photos/35582896/pexels-photo-35582896.jpeg?cs=srgb&dl=pexels-furkan-uslu-168786346-35582896.jpg&fm=jpg",
    licenseNote: "Fallback Istanbul landmark image while a Topkapi-specific photo is curated.",
  },
  "izmir-cesme-beach-wine-day-tour": {
    location: "Cesme",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/bodrum-coastal-view-with-turkish-flag-at-dusk-33822707/",
    imageUrl: "https://images.pexels.com/photos/33822707/pexels-photo-33822707.jpeg?cs=srgb&dl=pexels-orkun-uzunsac-1764951442-33822707.jpg&fm=jpg",
    licenseNote: "Fallback Aegean coast image while a Cesme-specific beach photo is curated.",
  },
  "konya-salt-lake-sultan-marshes-nature-tour": {
    location: "Konya / Tuz Golu",
    sourceName: "Pexels",
    sourcePage: "https://www.pexels.com/photo/stunning-travertine-terraces-of-pamukkale-34215958/",
    imageUrl: "https://images.pexels.com/photos/34215958/pexels-photo-34215958.jpeg?cs=srgb&dl=pexels-missptr-34215958.jpg&fm=jpg",
    licenseNote: "Fallback white landscape image while a Tuz Golu-specific photo is curated.",
  },
}
